### ISSUE TITLE
Query Logging For Optimization

### ISSUE THREAD

**Issue by jvnlee** [jvnlee/catch-dining#39]
## 개요

현재 애플리케이션에서 발생하는 쿼리들을 보다 자세하게 파악하고 문제점을 찾아 분석해보기 위해 필요한 데이터를 로깅해주는 모듈 개발

&nbsp;

## 문제 상황

쿼리 최적화를 진행하는데에 쓰일 현재의 로깅 정보가 한정적

```yaml
spring:
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace
        springframework:
          security: debug
```

- `spring.logging.level.org.hibernate.SQL: debug`: Hibernate에 의해 실행되는 모든 SQL 기록
  ```shell
  Hibernate: select user0_.id as id1_0_0_, user0_.name as name2_0_0_ from User user0_ where user0_.id=?
  ```

- `spring.logging.level.org.hibernate.type: trace`: Hibernate에서 Java 타입을 SQL 타입으로 변환하는 행동 및 대입 값 기록
  ```shell
  TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [VARCHAR] - value: [John Doe]
  ```

&nbsp;

이러한 정보 외에도 단일 요청 안에서 발생하는 쿼리의 개수, 처리 시간 등을 수집해야 어디서 성능 저하가 발생하는지 정확하게 파악할 수 있을 것으로 보임

- 쿼리 개수: 성능 저하를 유발하는 불필요한 JOIN, N+1 쿼리 등을 파악할 수 있는 지표

- 처리 시간: 성능 병목이 심한 API를 구분할 수 있는 지표
